In [ ]:
import numpy as np 
import pandas as pd 
import sys
from math import sqrt
import random
from sklearn.metrics import mean_squared_error,mean_absolute_error
import matplotlib.pyplot as plt
df = pd.read_csv('hasilrating.csv', ',')
print(df.head())

   id_wisata   id_user  rating
0          1   1118914       5
1          1   1925512       2
2          1   5618425       3
3          1   9144181       2
4          1  13212611       3


In [ ]:
df.sort_values(['rating','id_wisata'], ascending=[True, False])

id_wisata   id_user  rating
2766         29    111144       0
2770         29    119512       0
2789         29    546155       0
2803         29   1892619       0
2806         29   1991513       0
...         ...       ...     ...
243           3  51139121       5
245           3  51951214       5
251           3  91220222       5
24            2   2091002       5
0             1   1118914       5

[2866 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_wisata  2866 non-null   int64
 1   id_user    2866 non-null   int64
 2   rating     2866 non-null   int64
dtypes: int64(3)
memory usage: 67.3 KB


In [ ]:
df.to_csv('hasilrating.csv',index=False)

In [ ]:
n_wisata = df.id_wisata.unique().shape[0]
n_user = df.id_user.unique().shape[0]
print ('Total Wisata : '+ str(n_wisata))
print('Total User : ' + str(n_user))

Total Wisata : 29
Total User : 2389


In [ ]:
#result = df.pivot_table(index='id_wisata', 
                        #columns='metric_name', 
                        #values='angle_value')
#result.columns.name = None

In [ ]:
df_utility = df.pivot_table(index = 'id_wisata',columns='id_user',values = 'rating').fillna(0)
print(df_utility.head())
ratings = np.array(df_utility)
#sim = ratings.dot(ratings.T)
#sim
np.array([np.sqrt(np.diagonal(ratings))]) 

id_user    14        16        45        ...  98189181  99114111  99450438
id_wisata                                ...                              
1               0.0       0.0       0.0  ...       0.0       0.0       0.0
2               0.0       0.0       0.0  ...       0.0       0.0       0.0
3               0.0       5.0       0.0  ...       0.0       0.0       0.0
4               0.0       0.0       0.0  ...       0.0       0.0       0.0
5               0.0       0.0       0.0  ...       0.0       0.0       0.0

[5 rows x 2389 columns]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
df_utility

id_user    14        16        45        ...  98189181  99114111  99450438
id_wisata                                ...                              
1               0.0       0.0       0.0  ...       0.0       0.0       0.0
2               0.0       0.0       0.0  ...       0.0       0.0       0.0
3               0.0       5.0       0.0  ...       0.0       0.0       0.0
4               0.0       0.0       0.0  ...       0.0       0.0       0.0
5               0.0       0.0       0.0  ...       0.0       0.0       0.0
6               0.0       0.0       0.0  ...       0.0       0.0       0.0
7               0.0       0.0       0.0  ...       0.0       0.0       5.0
8               0.0       0.0       0.0  ...       0.0       0.0       0.0
9               0.0       0.0       0.0  ...       0.0       0.0       0.0
10              0.0       0.0       0.0  ...       0.0       0.0       0.0
11              0.0       0.0       0.0  ...       0.0       0.0       0.0
12              0.0       0.0       0.0  ...       0.0       0.0       0.0
13              0.0       0.0       0.0  ...       0.0       0.0       0.0
14              0.0       0.0       0.0  ...       0.0       0.0       0.0
15              0.0       0.0       0.0  ...       0.0       0.0       0.0
16              0.0       0.0       0.0  ...       0.0       0.0       0.0
17              0.0       0.0       0.0  ...       0.0       0.0       0.0
18              0.0       0.0       0.0  ...       0.0       0.0       0.0
19              0.0       0.0       2.0  ...       0.0       0.0       0.0
20              4.0       0.0       0.0  ...       0.0       0.0       0.0
21              0.0       3.0       0.0  ...       0.0       0.0       0.0
22              0.0       0.0       0.0  ...       0.0       0.0       0.0
23              0.0       4.0       0.0  ...       0.0       4.0       0.0
24              0.0       0.0       0.0  ...       0.0       0.0       0.0
25              0.0       0.0       0.0  ...       0.0       0.0       0.0
26              0.0       0.0       0.0  ...       0.0       0.0       0.0
27              0.0       0.0       0.0  ...       0.0       0.0       0.0
28              0.0       0.0       0.0  ...       0.0       0.0       0.0
29              0.0       0.0       0.0  ...       0.0       0.0       0.0

[29 rows x 2389 columns]

In [ ]:
#df_utility = df.pivot(index = 'id_wisata',columns='id_user',values = 'rating').fillna(0)
#print(df_utility.head())
#ratings = np.array(df_utility)
#sim = ratings.dot(ratings.T)
#sim
#np.array([np.sqrt(np.diagonal(ratings))]) 

In [ ]:
def train_test_split(ratings,fractionTest):
	test = np.zeros(ratings.shape)
	train = ratings.copy()
	for user in range(ratings.shape[0]):
		nonzeroarr = ratings[user,:].nonzero()[0]
		# print(nonzeroarr[0])
		nonzerolen = len(nonzeroarr)
		# print(nonzerolen)
		test_rating_indices = np.random.choice(nonzeroarr,size=int(nonzerolen*fractionTest),replace=False)
		train[user,test_rating_indices]=0
		test[user,test_rating_indices] = ratings[user,test_rating_indices]

	assert(np.all((train*test)==0))
	return train,test

In [ ]:
def predict(ratings,similarity):
	# Summation sim(u,u')*r(u',i) / Summation of |sim(u,u')|
	den = np.array(np.abs(similarity).sum(axis=1)).T
	den = den.reshape((den.shape[0],1))
	return similarity.dot(ratings) /den

In [ ]:
ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#def rmse_sim(mat):
	#sim_matrix = np.zeros((mat.shape[0],mat.shape[1]))
	#mean = np.mean(mat,axis=1)
	#for user in range(mat.shape[0]):
		#nonzeroarr = mat[user,:].nonzero()[0]
		#avg = np.sum(mat[user])/len(nonzeroarr)
		#sim_matrix[user,nonzeroarr] = mat[user,nonzeroarr] - avg + 1e-9
	
	#sim_matrix = (sim_matrix).dot((sim_matrix).T)
	#norms = np.array([np.sqrt(np.diagonal(np.abs(sim_matrix)))])
	# norms is a square root array of magnitude of each user (diagonal contains magntitude of rows)
	#return (sim_matrix / norms / norms.T)

In [ ]:
def cosine_sim(ratings, epsilon=1e-9):
    # epsilon -> small number for handling dived-by-zero errors
    sim = ratings.dot(ratings.T) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [ ]:
rating_array =cosine_sim(ratings, epsilon=1e-9)

In [ ]:
rating_array

array([[1.00000000e+00, 5.50983004e-12, 1.89003838e-12, 4.14855626e-12,
        3.20394353e-12, 4.60306814e-12, 3.49505102e-12, 7.72898160e-12,
        3.66322485e-12, 7.07460600e-12, 7.13267488e-12, 5.60243871e-12,
        1.14198118e-11, 7.58359592e-12, 6.90855560e-12, 6.87321749e-12,
        9.77017303e-12, 8.16170178e-12, 1.79765713e-12, 1.59898311e-12,
        1.48319639e-12, 4.93624065e-12, 1.56071968e-12, 4.45276404e-12,
        2.61867155e-12, 3.58112535e-12, 5.15820384e-12, 2.53136166e-12,
        2.66880256e-12],
       [5.50983004e-12, 1.00000000e+00, 4.49875739e-03, 2.46864671e-12,
        2.28785269e-02, 2.73910930e-12, 3.11965621e-02, 5.51906460e-02,
        5.01364259e-02, 4.20982668e-12, 4.24438124e-12, 2.00027784e-02,
        6.79549201e-12, 4.51270706e-12, 4.11101646e-12, 1.63599524e-02,
        3.48831314e-02, 4.85671568e-12, 1.06971681e-02, 8.56344169e-03,
        1.76518657e-03, 4.69978796e-02, 2.04319372e-02, 3.97450364e-02,
        1.55827100e-12, 2.13099034e-12,

In [ ]:
print(len(rating_array))

29


In [ ]:
ratingg=np.array(rating_array)

In [ ]:
df.reset_index(drop=True,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_wisata  2866 non-null   int64
 1   id_user    2866 non-null   int64
 2   rating     2866 non-null   int64
dtypes: int64(3)
memory usage: 67.3 KB


In [ ]:
output_df = pd.DataFrame({
    'id_wisata':df['id_wisata'],
    'id_user':df['id_user'],
    'rating':rating_array[0:1225798], 
})

Exception: ignored

In [ ]:
def get_rmse(pred, actual):
    # Ignore zero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return sqrt(mean_squared_error(pred, actual))

In [ ]:
import sys
import traceback

try:
    assert True
    assert 7 == 7
    assert 2 == 2
    # many more statements like this
except AssertionError:
    _, _, tb = sys.exc_info()
    traceback.print_tb(tb) # Fixed format
    tb_info = traceback.extract_tb(tb)
    filename, line, func, text = tb_info[-1]

    print('An error occurred on line {} in statement {}'.format(line, text))
    exit(1)

In [ ]:
split_ratio = [0.02]

for split in split_ratio:
    #print("\n\n\n\n")
    #print("split = ")
    #print(split)
    #print("\n\n\n")
    train,test = train_test_split(ratings,split) 
    print('Data splitted into Train,Test')

    sim_cos = cosine_sim(train)
    #sim_matrix = pearson_sim(train)

    print('Similarity Matrix Calulated')
    # print(sim_cos)
    # print(sim_matrix)

    user_prediction_cos_bias = predict(train, sim_cos)
    print ('Cosine Similarity RMSE: ' + str(get_rmse(user_prediction_cos_bias, test)))
    #print ('User-based CF MAE:(Cosine) ' + str(get_mae(user_prediction_cos_bias, test)))
    #user_prediction_pearson_bias = predict(train,sim_matrix)

Data splitted into Train,Test
Similarity Matrix Calulated
Cosine Similarity RMSE: 3.217332731444188
